name: flutter_revision
description: "Revised version of flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9



flutter:
  uses-material-design: true
  fonts:
    - family: JetBrains
      fonts:
        - asset: lib/fonts/JetBrainsMono-Regular.ttf
